
services:
  web:
    build: .
    container_name: csharpcontainer
    ports:
      - 8080:8080
    volumes:
      - app-data:/app

  nginx:
    build: ./nginx 
    container_name: nginx  
    ports:
      - 80:80
    depends_on:
      - web 

volumes:
  app-data:
